name: Guard
main: guard.Guard
version: 0.0.1
load: POSTWORLD
api-version: 1.13
authors:
  - Vagdedes2 (Du_bist_kein_Pro)
  - XIII___
description: Guard Anticheat in Java
softdepend:
  - Viaversion
  - ViaBackwards
commands:
  guard:
      description: Guard Command
      usage: /guard
      permission: guard